name: Fortify Security Scan

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * 6'

permissions:
  contents: write

jobs:
  Fortify-SAST:
    permissions:
      contents: write
      security-events: write
      pull-requests: write  # Add this line
    runs-on: ubuntu-latest
    
    steps:    
      - name: Check out source code
        uses: actions/checkout@v4
          
      - name: Run Fortify on Demand SAST & SCA Scan
        uses: fortify/github-action@v2
        with:
          sast-scan: true
          debricked-sca-scan: false
        env:
          SSC_URL: https://ssc.vincentdeng.net/ssc
          SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          SC_SAST_TOKEN: ${{secrets.SC_SAST_CLIENT_AUTH_TOKEN}}
          DO_SETUP: true
          DO_WAIT: true
          DO_POLICY_CHECK: true
          DO_JOB_SUMMARY: true
          DO_PR_COMMENT: true
